## InventoryScreen.gd
## Between-run item management. Reads items from GameState.active_run.inventory
## (Array of item Dictionaries generated by LootSystem). Shows rarity, slot,
## affixes, and value. Future: equip, discard, sell.
##
## Signals:
##   back_pressed   return to previous screen

class_name InventoryScreen
extends Control

signal back_pressed

#  Fonts
const _FONT_DISPLAY := preload("res://assets/fonts/TrajanPro-Regular.ttf")
const _FONT_HEADER  := preload("res://assets/fonts/Cinzel-Bold.ttf")
const _FONT_BODY    := preload("res://assets/fonts/IMFellEnglish-Regular.ttf")
const _FONT_UI      := preload("res://assets/fonts/CormorantGaramond-Regular.ttf")
const _FONT_MONO    := preload("res://assets/fonts/JetBrainsMono-Regular.ttf")

#  Design tokens
const _BG      := Color(0.031, 0.035, 0.051)
const _SURFACE := Color(0.067, 0.063, 0.047)
const _SURFACE2:= Color(0.102, 0.086, 0.063)
const _FG      := Color(0.941, 0.910, 0.816)
const _FG2     := Color(0.784, 0.722, 0.604)
const _DIM     := Color(0.353, 0.322, 0.278)
const _GOLD    := Color(0.831, 0.686, 0.275)

#  Rarity colours (mirrors LootSystem)
const _RARITY_COLORS := {
	"common":   Color(0.70, 0.76, 0.82),
	"uncommon": Color(0.30, 0.86, 0.50),
	"rare":     Color(0.98, 0.75, 0.14),
	"resonant": Color(0.75, 0.32, 0.97),
}

#  Slot labels
const _SLOT_LABELS := {
	"weapon":    "Weapon",
	"accessory": "Accessory",
	"charm":     "Charm",
}

#  State
var _items: Array     = []    # Array of LootSystem item Dictionaries
var _gold_count: int  = 0
var _filter: String   = "all" # "all" | "weapon" | "accessory" | "charm"

#  UI refs
var _grid:      GridContainer
var _count_lbl: Label
var _gold_lbl:  Label


func _ready() -> void:
	_load_items()
	_build_ui()


func _load_items() -> void:
	_items.clear()
	var gs: Node = get_node_or_null("/root/GameState")
	if gs and gs.get("active_run") != null:
		var run = gs.active_run
		if run.get("inventory") != null:
			_items = run.inventory.duplicate()
	# Also pull any pending loot from RunManager
	var rm: Node = get_node_or_null("/root/RunManager")
	if rm and rm.get("pending_loot") != null:
		for item in rm.pending_loot:
			if item not in _items:
				_items.append(item)

	var meta: Node = get_node_or_null("/root/MetaProgression")
	if meta:
		_gold_count = meta.get_currency(Currency.SOUL_SHARDS)

#  UI BUILD

func _build_ui() -> void:
	for c in get_children():
		c.queue_free()

	var bg := ColorRect.new()
	bg.color = _BG
	bg.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(bg)

	var scroll := ScrollContainer.new()
	scroll.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	add_child(scroll)

	var root := VBoxContainer.new()
	root.custom_minimum_size = Vector2(1100, 0)
	root.add_theme_constant_override("separation", 0)
	scroll.add_child(root)

	_build_header(root)
	_build_filter_bar(root)
	_space(root, 20)
	_build_grid(root)
	_space(root, 32)


func _build_header(root: VBoxContainer) -> void:
	var hdr := _solid_panel(root, _SURFACE2, Vector2(0, 80))
	var hh  := HBoxContainer.new()
	hh.add_theme_constant_override("margin_left", 40)
	hh.add_theme_constant_override("margin_right", 40)
	hh.alignment = BoxContainer.ALIGNMENT_CENTER
	hh.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	hdr.add_child(hh)

	var col := VBoxContainer.new()
	hh.add_child(col)
	_eyebrow(col, "PREPARATION")
	_lbl(col, "Inventory", 26, _FG, _FONT_DISPLAY)

	var stretch := Control.new()
	stretch.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	hh.add_child(stretch)

	# Shard counter
	var chip := _chip(_GOLD)
	hh.add_child(chip)
	_gold_lbl = Label.new()
	_gold_lbl.add_theme_font_override("font", _FONT_DISPLAY)
	_gold_lbl.add_theme_font_size_override("font_size", 13)
	_gold_lbl.add_theme_color_override("font_color", _GOLD)
	_gold_lbl.text = "Soul Shards: %d" % _gold_count
	chip.add_child(_gold_lbl)

	_hspace(hh, 12)

	# Item count chip
	var count_chip := _chip(Color(1, 1, 1, 0.12))
	hh.add_child(count_chip)
	_count_lbl = Label.new()
	_count_lbl.add_theme_font_override("font", _FONT_DISPLAY)
	_count_lbl.add_theme_font_size_override("font_size", 13)
	_count_lbl.add_theme_color_override("font_color", _FG2)
	_count_lbl.text = "%d Items" % _items.size()
	count_chip.add_child(_count_lbl)

	_hspace(hh, 12)

	var back := _iron_btn(" Back")
	back.pressed.connect(func() -> void: back_pressed.emit())
	hh.add_child(back)


func _build_filter_bar(root: VBoxContainer) -> void:
	var bar := _solid_panel(root, Color(0.05, 0.05, 0.07), Vector2(0, 44))
	var hbox := HBoxContainer.new()
	hbox.add_theme_constant_override("margin_left", 40)
	hbox.add_theme_constant_override("separation", 10)
	hbox.alignment = BoxContainer.ALIGNMENT_BEGIN
	hbox.set_anchors_and_offsets_preset(Control.PRESET_VCENTER_WIDE)
	bar.add_child(hbox)

	_lbl(hbox, "Filter:", 12, _DIM, _FONT_UI)

	var filters := [["all","All"], ["weapon","Weapons"], ["accessory","Accessories"], ["charm","Charms"]]
	for pair in filters:
		var fid: String    = str(pair[0])
		var flbl: String   = str(pair[1])
		var is_active      := _filter == fid
		var fbtn := Button.new()
		fbtn.text = flbl
		fbtn.add_theme_font_override("font", _FONT_UI)
		fbtn.add_theme_font_size_override("font_size", 13)
		var fc := _GOLD if is_active else _FG2
		fbtn.add_theme_color_override("font_color",       fc)
		fbtn.add_theme_color_override("font_hover_color", _GOLD)
		var st := StyleBoxFlat.new()
		st.bg_color     = _SURFACE.lightened(0.05) if is_active else Color(0, 0, 0, 0)
		st.border_color = _GOLD if is_active else Color(1, 1, 1, 0.12)
		for side in [SIDE_LEFT, SIDE_RIGHT, SIDE_TOP, SIDE_BOTTOM]:
			st.set_border_width(side, 1)
		st.content_margin_left = 12; st.content_margin_right  = 12
		st.content_margin_top  = 5;  st.content_margin_bottom = 5
		fbtn.add_theme_stylebox_override("normal", st)
		fbtn.pressed.connect(func() -> void: _set_filter(fid))
		hbox.add_child(fbtn)


func _build_grid(root: VBoxContainer) -> void:
	var grid_wrap := HBoxContainer.new()
	grid_wrap.add_theme_constant_override("margin_left", 40)
	grid_wrap.add_theme_constant_override("margin_right", 40)
	root.add_child(grid_wrap)

	var items_filtered := _items.filter(func(item: Dictionary) -> bool:
		return _filter == "all" or item.get("slot", "") == _filter)

	if items_filtered.is_empty():
		_build_empty_state(root)
		return

	_grid = GridContainer.new()
	_grid.columns = 3
	_grid.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_grid.add_theme_constant_override("h_separation", 16)
	_grid.add_theme_constant_override("v_separation", 16)
	grid_wrap.add_child(_grid)

	for item in items_filtered:
		_grid.add_child(_item_card(item))


func _build_empty_state(root: VBoxContainer) -> void:
	_space(root, 32)
	var pc := PanelContainer.new()
	pc.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	pc.custom_minimum_size = Vector2(0, 200)
	var st := StyleBoxFlat.new()
	st.bg_color     = _SURFACE
	st.border_color = Color(1, 1, 1, 0.06)
	for side in [SIDE_LEFT, SIDE_RIGHT, SIDE_TOP, SIDE_BOTTOM]:
		st.set_border_width(side, 1)
	st.content_margin_left = 40; st.content_margin_right = 40
	pc.add_theme_stylebox_override("panel", st)

	var empty_wrap := HBoxContainer.new()
	empty_wrap.add_theme_constant_override("margin_left", 40)
	empty_wrap.add_theme_constant_override("margin_right", 40)
	root.add_child(empty_wrap)
	empty_wrap.add_child(pc)

	var inner := VBoxContainer.new()
	inner.add_theme_constant_override("separation", 12)
	inner.add_theme_constant_override("margin_left",  40)
	inner.add_theme_constant_override("margin_right", 40)
	inner.add_theme_constant_override("margin_top",   40)
	pc.add_child(inner)

	var empty_title := Label.new()
	empty_title.text = "Empty Inventory" if _filter == "all" else "No %s" % _filter.capitalize() + "s found"
	empty_title.add_theme_font_override("font", _FONT_DISPLAY)
	empty_title.add_theme_font_size_override("font_size", 22)
	empty_title.add_theme_color_override("font_color", _FG2)
	inner.add_child(empty_title)

	var empty_body := Label.new()
	empty_body.text = "Complete missions to collect loot drops. Elite and boss encounters yield the rarest rewards." if _filter == "all" else "Switch filter to 'All' to see other item types."
	empty_body.add_theme_font_override("font", _FONT_BODY)
	empty_body.add_theme_font_size_override("font_size", 14)
	empty_body.add_theme_color_override("font_color", _DIM)
	empty_body.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	inner.add_child(empty_body)


func _item_card(item: Dictionary) -> PanelContainer:
	var rarity: String = str(item.get("rarity", "common"))
	var r_col: Color   = _RARITY_COLORS.get(rarity, _RARITY_COLORS["common"])

	var pc := PanelContainer.new()
	pc.custom_minimum_size = Vector2(0, 0)
	var st := StyleBoxFlat.new()
	st.bg_color     = _SURFACE
	st.border_color = r_col.lerp(Color.TRANSPARENT, 0.4)
	for side in [SIDE_LEFT, SIDE_RIGHT, SIDE_TOP, SIDE_BOTTOM]:
		st.set_border_width(side, 1)
	# Top accent stripe via expand offset trick
	st.border_width_top = 2
	st.border_color     = r_col.lerp(Color.TRANSPARENT, 0.2)
	pc.add_theme_stylebox_override("panel", st)

	var box := VBoxContainer.new()
	box.add_theme_constant_override("separation", 8)
	box.add_theme_constant_override("margin_left",   16)
	box.add_theme_constant_override("margin_right",  16)
	box.add_theme_constant_override("margin_top",    14)
	box.add_theme_constant_override("margin_bottom", 14)
	pc.add_child(box)

	# Header row: icon + rarity chip
	var hrow := HBoxContainer.new()
	hrow.add_theme_constant_override("separation", 10)
	box.add_child(hrow)

	var icon_lbl := Label.new()
	icon_lbl.text = str(item.get("icon", ""))
	icon_lbl.add_theme_font_size_override("font_size", 26)
	hrow.add_child(icon_lbl)

	var tags := VBoxContainer.new()
	tags.add_theme_constant_override("separation", 3)
	tags.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	hrow.add_child(tags)

	# Rarity label
	var r_lbl := Label.new()
	r_lbl.text = str(item.get("label", rarity.capitalize()))
	r_lbl.add_theme_font_override("font", _FONT_UI)
	r_lbl.add_theme_font_size_override("font_size", 11)
	r_lbl.add_theme_color_override("font_color", r_col)
	r_lbl.add_theme_constant_override("character_spacing", 2)
	tags.add_child(r_lbl)

	# Slot label
	var slot: String = str(item.get("slot", ""))
	var slot_lbl := Label.new()
	slot_lbl.text = _SLOT_LABELS.get(slot, slot.capitalize())
	slot_lbl.add_theme_font_override("font", _FONT_UI)
	slot_lbl.add_theme_font_size_override("font_size", 11)
	slot_lbl.add_theme_color_override("font_color", _DIM)
	tags.add_child(slot_lbl)

	# Item name
	var name_lbl := Label.new()
	name_lbl.text = str(item.get("name", "Unknown"))
	name_lbl.add_theme_font_override("font", _FONT_DISPLAY)
	name_lbl.add_theme_font_size_override("font_size", 15)
	name_lbl.add_theme_color_override("font_color", _FG)
	name_lbl.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	box.add_child(name_lbl)

	# Separator
	var sep := HSeparator.new()
	sep.add_theme_color_override("color", Color(1, 1, 1, 0.07))
	box.add_child(sep)

	# Affixes
	var affixes: Array = item.get("affixes", [])
	if affixes.is_empty():
		var none_lbl := Label.new()
		none_lbl.text = "No affixes."
		none_lbl.add_theme_font_override("font", _FONT_BODY)
		none_lbl.add_theme_font_size_override("font_size", 12)
		none_lbl.add_theme_color_override("font_color", _DIM)
		box.add_child(none_lbl)
	else:
		for af in affixes:
			var af_lbl := Label.new()
			af_lbl.text = " %s" % str(af.get("label", ""))
			af_lbl.add_theme_font_override("font", _FONT_MONO)
			af_lbl.add_theme_font_size_override("font_size", 12)
			af_lbl.add_theme_color_override("font_color", r_col.lerp(_FG2, 0.4))
			box.add_child(af_lbl)

	return pc

#  FILTER

func _set_filter(f: String) -> void:
	_filter = f
	_build_ui()   # Rebuild  filter bar recreates itself with new active state

#  WIDGET HELPERS

func _lbl(parent: Control, text: String, sz: int, color: Color, font: Font) -> Label:
	var l := Label.new()
	l.text = text
	l.add_theme_font_override("font", font)
	l.add_theme_font_size_override("font_size", sz)
	l.add_theme_color_override("font_color", color)
	parent.add_child(l)
	return l


func _eyebrow(parent: Control, text: String) -> Label:
	var l := Label.new()
	l.text = text
	l.add_theme_font_override("font", _FONT_UI)
	l.add_theme_font_size_override("font_size", 11)
	l.add_theme_color_override("font_color", _DIM)
	l.add_theme_constant_override("character_spacing", 4)
	parent.add_child(l)
	return l


func _chip(border: Color) -> PanelContainer:
	var pc := PanelContainer.new()
	var st := StyleBoxFlat.new()
	st.bg_color     = Color(0.12, 0.11, 0.08)
	st.border_color = border.lerp(Color.TRANSPARENT, 0.45)
	for side in [SIDE_LEFT, SIDE_RIGHT, SIDE_TOP, SIDE_BOTTOM]:
		st.set_border_width(side, 1)
	st.content_margin_left = 12; st.content_margin_right  = 12
	st.content_margin_top  = 4;  st.content_margin_bottom = 4
	pc.add_theme_stylebox_override("panel", st)
	return pc


func _solid_panel(parent: Control, color: Color, min_size: Vector2 = Vector2.ZERO) -> PanelContainer:
	var pc := PanelContainer.new()
	if min_size != Vector2.ZERO:
		pc.custom_minimum_size = min_size
	pc.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	var st := StyleBoxFlat.new()
	st.bg_color = color
	pc.add_theme_stylebox_override("panel", st)
	parent.add_child(pc)
	return pc


func _iron_btn(text: String) -> Button:
	var btn := Button.new()
	btn.text = text
	btn.add_theme_font_override("font", _FONT_DISPLAY)
	btn.add_theme_font_size_override("font_size", 12)
	btn.add_theme_color_override("font_color", _FG2)
	var st := StyleBoxFlat.new()
	st.bg_color     = _SURFACE
	st.border_color = Color(0.239, 0.208, 0.188, 0.6)
	for side in [SIDE_LEFT, SIDE_RIGHT, SIDE_TOP, SIDE_BOTTOM]:
		st.set_border_width(side, 1)
	st.content_margin_left = 14; st.content_margin_right  = 14
	st.content_margin_top  = 8;  st.content_margin_bottom = 8
	btn.add_theme_stylebox_override("normal", st)
	var hv := st.duplicate() as StyleBoxFlat
	hv.border_color = _GOLD
	btn.add_theme_stylebox_override("hover", hv)
	return btn


func _sep(parent: Control) -> void:
	var s := HSeparator.new()
	s.add_theme_color_override("color", Color(1, 1, 1, 0.07))
	parent.add_child(s)


func _space(parent: Control, h: int) -> void:
	var s := Control.new()
	s.custom_minimum_size = Vector2(0, h)
	parent.add_child(s)


func _hspace(parent: HBoxContainer, w: int) -> void:
	var s := Control.new()
	s.custom_minimum_size = Vector2(w, 0)
	parent.add_child(s)
